[package]
name = "game_of_life"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.87"
wasm-bindgen-test = "0.3.37"

[dependencies.web-sys]
version = "0.3.64"
features = [
    "console",
]