[workspace]

members = [
    "basic",
    "math",
    "collection",
    "advanced",
    "error",
    "functional",
    "test_crate",
    "smart_pointer",
    "object",
    "other",
    "concurrency",
    "grep",
]